from pydantic import BaseModel
from typing import List, Optional

class MinerInput(BaseModel):
    """
    A data model representing the input for the challenge.
    Contains the modified prompt and any additional context
    necessary for the miner to generate a response.
    """
    description: str  = "Generate a meaningful response to modified prompt that aligns with  original intent of  question."
    original_prompt: Optional[str] = None # original prompt, which is hidden from the miner for evaluation purposes
    modified_prompt: str  
    

class MinerOutput(BaseModel):
    """
    A data model representing the output generated by the miner.
    It contains the generated response and optional metadata.
    """
    response: str  
