from data_types import MinerInput, MinerOutput
from model import AIContentDetector


class Challenge:
    """
    A class that sets up the challenge and scores the miner's performance.
    It provides the task to be completed and evaluates the output.
    """

    model = AIContentDetector()

    def prepare_task(self) -> MinerInput:
        """
        Prepares the task by returning an instance of MinerInput,
        which contains the task description.
        """
        return MinerInput()

    def score_task(self, miner_input: MinerInput, miner_output: MinerOutput) -> float:
        """
        Evaluates the output generated by the miner.
        If the generated text contains the word 'AI', it returns a score of 1.0.
        Otherwise, it returns 0.0.
        """
        real_prob = self.model.find_real_prob(miner_output.text)
        return 1.0 if real_prob > 0.5 else 0.0
