from pydantic import BaseModel


class MinerInput(BaseModel):
    """
    A data model representing the input for the challenge.
    Contains a description of the task that the miner should perform.
    """

    description: str = "Generate a human-like text"


class MinerOutput(BaseModel):
    """
    A data model representing the output generated by the miner.
    It contains the generated text.
    """

    text: str
